apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: cGFzc3dvcmQ=  # Replace with base64 encoded PostgreSQL password
  MARIADB_DATABASE: bWFnYXNpbg==  # Replace with base64 encoded PostgreSQL database name
  MARIADB_ROOT_USER: cm9vdA==