version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_local
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d  # monte les scripts SQL ici
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_local
    environment:
      PMA_HOST: mariadb_local
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8990:80"
    restart: unless-stopped
    depends_on:
      - mariadb

volumes:
  mariadb_data:
